/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenOptions {
  dataPath: string
}
export interface TripleOutput {
  subjectId: bigint
  predicateId: bigint
  objectId: bigint
}
export interface TripleInput {
  subjectId: bigint
  predicateId: bigint
  objectId: bigint
}
export interface QueryCriteriaInput {
  subjectId?: bigint
  predicateId?: bigint
  objectId?: bigint
}
export interface CursorId {
  id: bigint
}
export interface CursorBatch {
  triples: Array<TripleOutput>
  done: boolean
}
export interface FactOutput {
  subject: string
  predicate: string
  object: string
  subjectId: bigint
  predicateId: bigint
  objectId: bigint
}
export interface FactCursorBatch {
  facts: Array<FactOutput>
  done: boolean
}
export interface PathResultOutput {
  path: Array<bigint>
  cost: number
  hops: number
}
export interface PageRankEntryOutput {
  nodeId: bigint
  score: number
}
export interface PageRankResultOutput {
  scores: Array<PageRankEntryOutput>
  iterations: number
  converged: boolean
}
export declare function open(options: OpenOptions): NapiResult
export declare class DatabaseHandle {
  addFact(subject: string, predicate: string, object: string): NapiResult
  deleteFact(subject: string, predicate: string, object: string): NapiResult
  batchAddFacts(triples: Array<TripleInput>): NapiResult
  batchDeleteFacts(triples: Array<TripleInput>): NapiResult
  intern(value: string): NapiResult
  resolveId(value: string): NapiResult
  resolveStr(id: bigint): NapiResult
  getDictionarySize(): NapiResult
  executeQuery(query: string, params?: object | undefined | null): NapiResult
  prepareV2(query: string, params?: object | undefined | null): NapiResult
  setNodeProperty(nodeId: bigint, json: string): NapiResult
  /** Set node properties directly from JS object (v1.1 - bypasses JSON string) */
  setNodePropertyDirect(nodeId: bigint, properties: any): NapiResult
  getNodeProperty(nodeId: bigint): NapiResult
  /** Get node properties directly as JS object (v1.1 - bypasses JSON string) */
  getNodePropertyDirect(nodeId: bigint): NapiResult
  setEdgeProperty(subjectId: bigint, predicateId: bigint, objectId: bigint, json: string): NapiResult
  /** Set edge properties directly from JS object (v1.1 - bypasses JSON string) */
  setEdgePropertyDirect(subjectId: bigint, predicateId: bigint, objectId: bigint, properties: any): NapiResult
  getEdgeProperty(subjectId: bigint, predicateId: bigint, objectId: bigint): NapiResult
  /** Get edge properties directly as JS object (v1.1 - bypasses JSON string) */
  getEdgePropertyDirect(subjectId: bigint, predicateId: bigint, objectId: bigint): NapiResult
  query(criteria?: QueryCriteriaInput | undefined | null): NapiResult
  queryFacts(criteria?: QueryCriteriaInput | undefined | null): NapiResult
  hydrate(dictionary: Array<string>, triples: Array<TripleInput>): NapiResult
  openCursor(criteria?: QueryCriteriaInput | undefined | null): NapiResult
  readCursor(cursorId: bigint, batchSize: number): NapiResult
  readCursorFacts(cursorId: bigint, batchSize: number): NapiResult
  closeCursor(cursorId: bigint): NapiResult
  beginTransaction(): NapiResult
  commitTransaction(): NapiResult
  abortTransaction(): NapiResult
  close(): NapiResult
  /** BFS shortest path (unweighted) */
  bfsShortestPath(startId: bigint, endId: bigint, predicateId?: bigint | undefined | null, maxHops?: number | undefined | null, bidirectional?: boolean | undefined | null): NapiResult
  /** Dijkstra shortest path (weighted, uniform weight = 1.0) */
  dijkstraShortestPath(startId: bigint, endId: bigint, predicateId?: bigint | undefined | null, maxHops?: number | undefined | null): NapiResult
  /** PageRank algorithm */
  pagerank(predicateId?: bigint | undefined | null, damping?: number | undefined | null, maxIterations?: number | undefined | null, tolerance?: number | undefined | null): NapiResult
}
export declare class StatementHandle {
  step(): NapiResult
  columnCount(): NapiResult
  columnName(column: number): NapiResult
  columnType(column: number): NapiResult
  columnText(column: number): NapiResult
  columnFloat(column: number): NapiResult
  columnBool(column: number): NapiResult
  columnNodeId(column: number): NapiResult
  columnRelationship(column: number): NapiResult
  finalize(): NapiResult
}
