pub mod api;
pub mod backup;
pub mod blob_store;
pub mod bulkload;
pub mod csr;
pub mod engine;
mod error;
pub mod idmap;
pub mod index;
pub mod label_interner;
pub mod memtable;
pub mod pager;
pub mod property;
mod read_path_api_iter;
mod read_path_api_props;
mod read_path_api_stats;
mod read_path_convert;
mod read_path_engine_idmap;
mod read_path_engine_labels;
mod read_path_engine_view;
mod read_path_iters;
mod read_path_labels;
mod read_path_neighbors;
mod read_path_nodes;
mod read_path_overlay;
mod read_path_property_store;
mod read_path_run_edges;
mod read_path_run_iters;
mod read_path_run_property_maps;
mod read_path_run_props;
mod read_path_run_state;
mod read_path_stats;
mod read_path_symbols;
mod read_path_tombstones;
pub mod snapshot;
pub mod stats;
pub mod vacuum;
pub mod wal;

pub use crate::error::{Error, Result};

pub const PAGE_SIZE: usize = 8192;
pub const FILE_MAGIC: [u8; 16] = *b"NERVUSDBv2\x00\x00\x00\x00\x00\x00";
pub const VERSION_MAJOR: u32 = 2;
pub const VERSION_MINOR: u32 = 0;
pub const STORAGE_FORMAT_EPOCH: u64 = 1;
